title: NangManCat`s Lab
markdown: kramdown
theme: minima
collections:
  _pages:
    output: true
    permalink: /:name/

# 페이지네이션 설정
paginate: 6
paginate_path: "/page/:num/"
pagination_dir: page

# 플러그인 설정
plugins:
  - jekyll-paginate

# GitHub Pages와 호환성 설정
safe: true
whitelist:
  - jekyll-paginate
